#!/bin/bash

set -o errexit
set -o nounset

readonly API_URL='https://cjp.sbmr.in/api/raw'
readonly ABOUT_URL='https://cjp.sbmr.in/about/'

function _help() {
	echo -e "
ayashii -- AYASHII NIHONGO cli

USAGE
    ayashii TEXT   # Convert from normal Japanese text to AYASHII NIHONGO.
    ayashii --help # Show this help.

EXAMPLE
    $ ayashii これは正しい日本語です！
    これは正レい日本语てず！

DEPENDENCE
    - curl  Required for API calls.
    - nkf   Required for URL encoding.

API
    Using this API. thanks!: ${API_URL}
    To see more info about this API, visit: ${ABOUT_URL}

REPO
    https://github.com/sheepla/ayashii-cli
    Author: sheepla  https://github.com/sheepla
    Licence: MIT
"
}

function _err() {
	echo -e "[\e[31m ERR \e[m] ${*}"
}

function _test_cmd() {
	for cmd in "${@}"; do
		if ! command -v "${cmd}" &>/dev/null; then
			_err "${cmd} command not found. Please install it."
			return 1
		fi
	done
}

function _encode() {
    # https://qiita.com/ik-fib/items/cc983ca34600c2d633d5
    nkf -WwMQ <<< "${*}" | sed 's/=$//g' | tr = % | tr -d '\n' || {
        _err 'Encoding failed.'
    }
    #elif _test_cmd euarel
    #    # https://qiita.com/ik-fib/items/cc983ca34600c2d633d5
    #    euarel --encode <<< "${*}" || {
    #        _err 'Encoding failed.'
    #        exit 1
    #    }
}

function _main() {
	if [ $# -lt 1 ]; then
		_help
		return 0
	fi

	for arg in "${@}"; do
		if [ "${arg}" = '--help' ]; then
			_help
			return 0
		fi
	done

	_test_cmd curl nkf || exit 1

	text="${*}"
	encoded_text=$(_encode "${text}")
	curl --silent "${API_URL}/${encoded_text}" --request GET
	return 0
}

_main "$@"
exit "${?}"
