#!/bin/bash

set -o errexit
set -o nounset

readonly API_URL='https://cjp.sbmr.in/api/raw'
readonly ABOUT_URL='https://cjp.sbmr.in/about/'
readonly AUTHOR_URL='https://github.com/sheepla'
readonly REPO_URL="${AUTHOR_URL}/ayashii-cli"

function _help() {
	echo -e "
ayashii -- AYASHII NIHONGO CLI: Convert from normal Japanese text to AYASHII NIHONGO.

USAGE
    ayashii TEXT        # from arguments
    echo TEXT | ayashii # from stdin
    ayashii --help      # Show this help.

EXAMPLE
    $ ayashii これは正しい日本語です！
    これは正レい日本语てず！
    $ echo これは正しい日本語です！ | ayashii
    これは正レい日本语てず！

DEPENDENCE
    - curl  Required for API calls.

API
    Using this API. thanks!: ${API_URL}
    To see more info about this API, visit: ${ABOUT_URL}

REPO
    Repository:      ${REPO_URL}
    Author: sheepla  ${AUTHOR_URL}
    Licence:         MIT
"
}

function _err() {
	echo -e "[\e[31m ERR \e[m] ${*}"
}

function _test_cmd() {
	for cmd in "${@}"; do
		if ! command -v "${cmd}" &>/dev/null; then
			_err "${cmd} command not found. Please install it."
			return 1
		fi
	done
}

function _encode() {
	echo -n "${*}" | od -tx1 -An | tr ' ' % | tr -d \\n
}

function _to_ayashii() {
	text="${*}"
	curl --silent "${API_URL}/$(_encode "${text}")" --request GET |
		awk 4 | # Add a line break at the end
		sed -e "s_%3a_:_g" -e "s_%2f_/_g"
}

function _main() {
	if [ -p /dev/stdin ]; then
		_test_cmd curl || exit 1
		_to_ayashii "$(cat /dev/stdin)"
		return "${?}"
	fi

	if [ "${#}" -lt 1 ]; then
		_help
		_err "Must require arguments..."
		return 1
	fi

	for arg in "${@}"; do
		if [ "${arg}" = '--help' ]; then
			_help
			return 0
		fi
	done

	_test_cmd curl || exit 1
	_to_ayashii "${*}"
	return "${?}"
}

_main "$@"
exit "${?}"
